name: tourism
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.0.0+7

environment:
  sdk: ">=2.14.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  shared_preferences: ^2.0.13
  image_picker: ^0.8.5
  uuid: ^3.0.6
  url_launcher: ^6.0.20
  flutter_widget_from_html_core: ^0.8.5
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  toast: ^0.2.9
  webview_flutter: ^3.0.2
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6
  connectivity_plus: ^2.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with our application, so that we can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/abstract.png
    - assets/images/app_logo.png
    - assets/images/default_user.png
    - assets/images/image_placeholder.webp
    - assets/images/no_internet_connection.webp
    - assets/images/server_maintenance.webp
    - assets/images/youtube.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.otf
        - asset: assets/fonts/NotoSans-Bold.otf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
